### ISSUE TITLE
Category function caused by the error

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion-plugin-portfolio#3]
Added classification no problem, but the increase in classification, access from the front page, click on the open when it is 404 error page, indicating that the template file is wrong or missing, want to correct.

**Comment by gesonchi** [comment]
bug：

portfolio plugin does not support category classification of numeric names. Open will appear 404.

**Comment by semchishinv** [comment]
@gesonchi Hello! Thank you for report

This issue was resolved in latest version of Portfolio Plugin, find screenshot below.

![image](https://user-images.githubusercontent.com/30542757/60409322-f6625900-9be4-11e9-9b8b-33f9517e6405.png)

**Comment by vbezruchkin** [comment]
Thanks @semchishinv
